import { Validators } from "@angular/forms";

export const usuariosForm = {
  nombre: ['',[Validators.required, Validators.minLength(3)]],
  ap_paterno: ['',[Validators.required, Validators.minLength(3)]],
  ap_materno: ['',[Validators.required, Validators.minLength(3)]],
  fecha_nacimiento: ['',[Validators.required]],
  genero: ['',[Validators.required]],
  fecha_inscripcion: ['',[Validators.required]],
  fecha_alta: ['',[Validators.required]],
  rfc: ['',[Validators.required,  Validators.minLength(14), Validators.maxLength(14)]],
  curp: ['',[Validators.required, Validators.minLength(18), Validators.maxLength(18)]],
  nss: ['',[Validators.required, Validators.minLength(8), Validators.maxLength(8)]],
  tel_cel: ['',[Validators.required, Validators.maxLength(10)]],
  email: ['',[Validators.required, Validators.email]],
  tipo_sangre: ['',[Validators.required]],
  licencia: ['',[Validators.required]],
  alergias: ['',[Validators.required]],
  padecimientos: ['',[Validators.required]],
  nacionalidad: ['',[Validators.required]],
  calle: ['',[Validators.required]],
  numero: ['',[Validators.required]],
  colonia: ['',[Validators.required]],
  cp: ['',[Validators.required]],
  municipio: ['',[Validators.required]],
  ciudad: ['',[Validators.required]],
  pais: ['',[Validators.required]],
  referencia_directa: ['',[Validators.required]],
  comment: ['',[Validators.required]],
  status: ['',[Validators.required]],
  id_tipo_rol: ['',[Validators.required]],
  id_locales:[''],
  id_gastos:[''],
  id_camiones:[''],
  id_carritos:[''],
  id_abonos:[''],
  id_creditos:[''],
  id_ventas:[''],
  id_historiales:[''],
  id_metodo_pagos:['']
}
